name: Create new cohort

on:
  issues:
    types: labeled

env:
  GH_TOKEN: ${{ secrets.GH_PAT }}

jobs:

  parse_issue:
    if: ${{ github.event.label.name == 'cohort' }}
    name: Parse Issue data
    runs-on: ubuntu-latest
    outputs:
      org: ${{ steps.extract.outputs.org }}
      lesson_repo: ${{ steps.extract.outputs.repo }}
      assignments: ${{ steps.extract.outputs.assignments }}
      instructors: ${{ steps.extract.outputs.instructors }}
      students: ${{ steps.extract.outputs.students }}
    steps:
      - name: Parse issue
        id: parse
        uses: zentered/issue-forms-body-parser@v2.1.1
      - name: Extract relevant fields
        id: extract
        run: |
          echo "org=$(echo $ISSUE_DATA | jq -r '."organization-name".content|.[]')" >> $GITHUB_OUTPUT
          echo "repos=$(echo $ISSUE_DATA | jq -r '."lesson-repos".content' sed 's/\\r\\n/", "/g')" >> $GITHUB_OUTPUT
          # Using sed to format output as an array
          echo "assignments=$(echo $ISSUE_DATA | jq -c '."list-of-assignments".content' | sed 's/\\r\\n/", "/g')" >> $GITHUB_OUTPUT
          echo "instructors=$(echo $ISSUE_DATA | jq -c '."list-of-instructors".content' | sed -e 's/\\r\\n/ /g' -e 's/[^[:alnum:] @.-]//g')" >> $GITHUB_OUTPUT
          echo "students=$(echo $ISSUE_DATA | jq -c '."list-of-students".content' | sed -e 's/\\r\\n/ /g' -e 's/[^[:alnum:] @.-]//g')" >> $GITHUB_OUTPUT
        env:
          ISSUE_DATA: ${{ steps.parse.outputs.data }}
      - name: Show output
        run: |
          echo ${{ toJson(steps.parse.outputs.data) }} >> "parse_data.json"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: parse-data
          path: parse_data.json

  # TODO: refactor so that all the `create_*_repo` jobs are in a single job
  create_lesson_repo:
    name: Fork lesson repos
    needs: parse_issue
    runs-on: ubuntu-latest
    env:
      ORG: ${{ needs.parse_issue.outputs.org }}
    steps:
      - name: Fork lesson repos
        if: needs.parse_issue.outputs.lesson_repos != '*No response*'
        run: |
          for repo in $(echo ${{ needs.parse_issue.outputs.lesson_repos }}); do
            gh repo fork ${{ github.repository_owner }}/${repo} --org ${{ env.ORG }}
          done

  create_assignment_repos:
    name: Fork assignment repos
    needs: parse_issue
    runs-on: ubuntu-latest
    env:
      ORG: ${{ needs.parse_issue.outputs.org }}
    steps:
      - name: Fork assignment repos
        if: needs.parse_issue.outputs.assignments != '*No response*'
        run: |
          for assignment in $(echo ${{ needs.parse_issue.outputs.assignments }}); do
            gh repo fork ${{ github.repository_owner }}/${assignment} --org ${{ env.ORG }}
          done

  create_discussions_repo:
    name: Create Discussions repo
    needs: parse_issue
    runs-on: ubuntu-latest
    env:
      ORG: ${{ needs.parse_issue.outputs.org }}
    steps:
      - name: Create Discussions repo
        run: |
          gh api -X POST /orgs/${{ env.ORG }}/repos \
          --input <(echo '{"name": "Discussions", "description": "Discussion forum for this cohort", \
            "private": true, "has_discussions": true, "team_id": "Students"}')

  invite_members:
    name: Invite students and instructors to org
    needs: parse_issue
    runs-on: ubuntu-latest
    env:
      ORG: ${{ needs.parse_issue.outputs.org }}
    steps:
      - name: Create Students team
        continue-on-error: true # if the team already exists, this will fail
        run: |
          gh api -X POST /orgs/${{ env.ORG }}/teams \
          --input <(echo '{"name": "Students", "description": "Students in this cohort", "privacy": "closed"}')
      - name: Invite instructors to Students team as maintainer # this should also invite them to the org
        run: |
          for instructor in $(echo ${{ needs.parse_issue.outputs.instructors }}); do
            gh api -X PUT /orgs/${{ env.ORG }}/teams/Students/memberships/${instructor} \
            --input <(echo '{"role": "maintainer"}')
          done
      - name: Invite students to Students team as member # this should also invite them to the org
        run: |
          for student in $(echo ${{ needs.parse_issue.outputs.students }}); do
            gh api -X PUT /orgs/${{ env.ORG }}/teams/Students/memberships/${student} \
            --input <(echo '{"role": "member"}')
          done
