name: Create new cohort

on:
  issues:
    types: labeled

env:
  GH_TOKEN: ${{ secrets.GH_PAT }}

jobs:

  parse_issue:
    if: ${{ github.event.label.name == 'cohort' }}
    name: Parse Issue data
    runs-on: ubuntu-latest
    outputs:
      data: ${{ steps.parse.outputs.data }}
    steps:
      - name: Parse issue
        id: parse
        uses: zentered/issue-forms-body-parser@v2.1.1
      - name: Show output
        run: |
          echo ${{ toJson(steps.parse.outputs.data) }} >> "parse_data.json"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: parse-data
          path: parse_data.json

  create_repo:
    name: Create new GitHub repos
    needs: parse_issue
    runs-on: ubuntu-latest
    env:
      ISSUE_DATA: ${{ needs.parse_issue.outputs.data }}
    steps:
      - name: Extract JSON fields
        id: extract
        run: |
          echo "org=" $(echo $ISSUE_DATA | jq -r '."organization-name".content|.[]') >> $GITHUB_OUTPUT
          echo "repo=" $(echo $ISSUE_DATA | jq -r '."lesson-repository".content|.[]') >> $GITHUB_OUTPUT
      - name: Fork lesson repo
        run: |
          # gh repo fork ${{ github.repository_owner }}/${{ steps.extract.outputs.repo }} --org ${{ steps.extract.outputs.org }}
          echo ${{ github.repository_owner }}/${{ steps.extract.outputs.repo }}
