name: Create new cohort

on:
  workflow_dispatch:
    inputs:
      org-name:
        description: What is the name of the organization?
        required: true
        default: ''
      repo-name:
        description: What is the name of the repository?
        required: true
        default: ''

jobs:
  create_repo:
    name: Create new GitHub repo
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}

    steps:
        - name: Check out repo
          uses: actions/checkout@v3
        - name: Create repo
          run: |
            gh repo create ${{ github.event.inputs.org-name }}/${{ github.event.inputs.repo-name }} --private
