name: Create new cohort

on:
  issues:
    types: labeled

env:
  GH_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  parse_issue:
    if: ${{ github.event.label.name == 'cohort' }}
    name: Parse Issue data
    runs-on: ubuntu-latest
    outputs:
      data: ${{ steps.parse.outputs.data }}
    steps:
      - name: Parse issue
        id: parse
        uses: zentered/issue-forms-body-parser@v2.1.1
      - name: Show output
        run: |
          echo ${{ toJson(steps.parse.outputs.data) }} >> "parse_data.json"
          cat parse_data.json
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: parse-data
          path: parse_data.json

  create_repo:
    name: Create new GitHub repo
    needs: parse_issue
    runs-on: ubuntu-latest
    steps:
      - env:
          ISSUE_DATA: ${{ fromJson(needs.parse_issue.outputs.data) }}
        run: echo "$ISSUE_DATA"
        # - name: Create repo
        #   run: |
        #     gh repo create ${{ github.event.inputs.org-name }}/${{ github.event.inputs.repo-name }} --private
