name: Create new cohort

on:
  issues:
    types: labeled

jobs:
  parse_issue:
    if: ${{ github.event.label.name == 'cohort' }}
    name: Parse Issue data
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - name: Parse issue
        id: parse
        uses: zentered/issue-forms-body-parser@v2.1.1
      - name: Show output
        run: echo ${{ fromJson(steps.parse.outputs.data) }}
  # create_repo:
  #   name: Create new GitHub repo
  #   runs-on: ubuntu-latest
  #   env:
  #     GH_TOKEN: ${{ secrets.GH_PAT }}

  #   steps:
  #       # - name: Create repo
  #       #   run: |
  #       #     gh repo create ${{ github.event.inputs.org-name }}/${{ github.event.inputs.repo-name }} --private
